# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Volume Average', kernelModule='Volume_Average', kernelFunction='generate_ss_curve', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgVerticalFrame(name='VFrame_1', p='DialogBox', layout='LAYOUT_FILL_X|LAYOUT_FILL_Y', pl=0, pr=0, pt=0, pb=0)
RsgFileTextField(p='VFrame_1', ncols=25, labelText='Odb file                :', keyword='Odb_Path', default='', patterns='All files (*)')
RsgFileTextField(p='VFrame_1', ncols=25, labelText='Output file            :', keyword='Output_Path', default='', patterns='All files (*)')
RsgTextField(p='VFrame_1', fieldType='Float', ncols=10, labelText='Nominal strain       :', keyword='EngStrain', default='0.0')
RsgComboBox(name='ComboBox_2', p='VFrame_1', text='Stress component  :', keyword='S_Comp', default='S11', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_2', text='S11')
RsgListItem(p='ComboBox_2', text='S22')
RsgListItem(p='ComboBox_2', text='S33')
RsgListItem(p='ComboBox_2', text='S12')
RsgListItem(p='ComboBox_2', text='S13')
RsgListItem(p='ComboBox_2', text='S23')
RsgCheckButton(p='VFrame_1', text='Plot curve on OK', keyword='Plot_Flag', default=True)
dialogBox.show()